# Configurations
title:            FastStarter
longtitle:        FastStarter
author:           FastStarter
# email:            sighingnow@gmail.com
description: >
  I am a Java developer and also an independent software developer. 
  我是一名Java开发者, 也是一名独立软件开发者。

version:          1.0
gitbook_version:  3.2.3

# url:              'https://cheneyzhang.me'
baseurl:          '/docs'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  # pages:
    # output: true
    # permalink: /:collection/:path/
  # others:
    # output: true
    # permalink: /:collection/:path/
  faststarter:
    output: true
    # permalink: /:collection/:path/
  faq:
    output: true

ordered_collections:
  - faq
  # - pages
  # - others
  - faststarter
  - posts

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-sitemap